<?xml version="1.0" encoding="utf-8"?><Database Name="db_ICBF" Class="ORMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Acudientes" Member="Acudientes">
    <Type Name="Acudientes">
      <Column Name="idAcudiente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cedula" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Acudientes_Ninos" Member="Ninos" ThisKey="idAcudiente" OtherKey="idAcudiente" Type="Ninos" />
      <Association Name="Usuarios_Acudientes" Member="Usuarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rol" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idDatosBasicos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuarios_Acudientes" Member="Acudientes" ThisKey="idUsuario" OtherKey="idUsuario" Type="Acudientes" />
      <Association Name="DatosBasicos_Usuarios" Member="DatosBasicos" ThisKey="idDatosBasicos" OtherKey="idDatosBasicos" Type="DatosBasicos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Asistencias" Member="Asistencias">
    <Type Name="Asistencias">
      <Column Name="idAsistencia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="estadoNino" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idNino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ninos_Asistencias" Member="Ninos" ThisKey="idNino" OtherKey="idNino" Type="Ninos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AvancesAcademicos" Member="AvancesAcademicos">
    <Type Name="AvancesAcademicos">
      <Column Name="idAvanceAcademico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="anioEscolar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nivel" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="notas" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fechaEntrega" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idNino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ninos_AvancesAcademicos" Member="Ninos" ThisKey="idNino" OtherKey="idNino" Type="Ninos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatosBasicos" Member="DatosBasicos">
    <Type Name="DatosBasicos">
      <Column Name="idDatosBasicos" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="celular" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="NChar(80) NOT NULL" CanBeNull="false" />
      <Association Name="DatosBasicos_Usuarios" Member="Usuarios" ThisKey="idDatosBasicos" OtherKey="idDatosBasicos" Type="Usuarios" />
      <Association Name="DatosBasicos_Ninos" Member="Ninos" ThisKey="idDatosBasicos" OtherKey="idDatosBasicos" Type="Ninos" />
    </Type>
  </Table>
  <Table Name="dbo.EPS" Member="EPS">
    <Type Name="EPS">
      <Column Name="idEps" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EPS_Ninos" Member="Ninos" ThisKey="idEps" OtherKey="idEps" Type="Ninos" />
    </Type>
  </Table>
  <Table Name="dbo.Jardines" Member="Jardines">
    <Type Name="Jardines">
      <Column Name="idJardin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="NChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Jardines_Ninos" Member="Ninos" ThisKey="idJardin" OtherKey="idJardin" Type="Ninos" />
    </Type>
  </Table>
  <Table Name="dbo.Ninos" Member="Ninos">
    <Type Name="Ninos">
      <Column Name="idNino" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NUIP" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="tipoSangre" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ciudadNacimiento" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estatura" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="idJardin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAcudiente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idDatosBasicos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEps" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ninos_Asistencias" Member="Asistencias" ThisKey="idNino" OtherKey="idNino" Type="Asistencias" />
      <Association Name="Ninos_AvancesAcademicos" Member="AvancesAcademicos" ThisKey="idNino" OtherKey="idNino" Type="AvancesAcademicos" />
      <Association Name="Acudientes_Ninos" Member="Acudientes" ThisKey="idAcudiente" OtherKey="idAcudiente" Type="Acudientes" IsForeignKey="true" />
      <Association Name="DatosBasicos_Ninos" Member="DatosBasicos" ThisKey="idDatosBasicos" OtherKey="idDatosBasicos" Type="DatosBasicos" IsForeignKey="true" />
      <Association Name="EPS_Ninos" Member="EPS" ThisKey="idEps" OtherKey="idEps" Type="EPS" IsForeignKey="true" />
      <Association Name="Jardines_Ninos" Member="Jardines" ThisKey="idJardin" OtherKey="idJardin" Type="Jardines" IsForeignKey="true" />
    </Type>
  </Table>
</Database>